version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: franchise-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: franchise_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - franchise-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/franchise_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  franchise-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchise-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/franchise_db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - franchise-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  franchise-network:
    driver: bridge
